test-kitchen/kitchen-vagrant

README.md

Small update to readme on how to enable GUI inside TK YAML.
Source: https://github.com/test-kitchen/kitchen-vagrant/pull/74
Why? Troubleshooting Windows with gui is just simpler, however enabling GUI in kitchen.yaml wasn't very clear.

Update README.md with GUI info for Windows support

---

README.md
lib/kitchen/driver/vagrant.rb

Able to run vagrant up if we set the provision flad
Needed in case of you want to include a vagrantfile like this
```ruby
Vagrant.configure(2) do |config|
config.vm.provision :shell do |shell|
shell.inline = %Q{
}
end
end
```

Provision option

---

.travis.yml
Gemfile
Guardfile
Rakefile
kitchen-vagrant.gemspec
lib/kitchen/driver/vagrant.rb

This PR is intended to bring the code quality/metrics support up to that of Test Kitchen core. This includes:

Project quality freshening

---

lib/kitchen/driver/vagrant.rb

The explosion of tunables is making it harder to track what is available. Here's an attempt at some cleanup.

Tidy default config attributes

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

The default values for the `:box` and `:box_url` attributes were always
implicitly based on the Bento project's base boxes
(https://github.com/chef/bento). This meant that for a small number of
common/known platforms, the box name and URLs could be pre-calculated to
help with initial out-of-the-box experience.
For example, given a platform name of `"ubuntu-14.04"`, a default box
name of `"opscode-ubuntu-14.04"` and box URL could be computed (but only
for VirtualBox or VMware-based providers). Any custom platform name
would have to explicitly override the default value for at least `:box`
if not also for `:box_url`.
This commit makes the implicit default code for Bento boxes explicit. In
other words, if your platform name does not match the pre-defined Bento
box platforms, the default of …

Only set custom `:box` & `:box_url` values for known Bento boxes.

---

README.md
kitchen-vagrant.gemspec
lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

For the moment, we're going to pin to the 1.4.0.beta.1 release of Test Kitchen as any other releases may be incompatible. This will be relaxed for the final release.

Support for WinRM Transport and Windows-based instances

---

README.md
lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

It turns out that the IP address of the Vagrant VM returned by the
`vagrant ssh-config` varies with each Vagrant provider and so can't be
relied on to return a private/nat'ed address. In some cases
`"127.0.0.1"` is returned and the locally forward port is returned for
the port number.
To resolve this, the `vagrant-winrm` Vagrant plugin will be used,
exposing a `vagrant winrm-config` subcommand to return WinRM-specific
connection details of the form:
Host CustomHostname
HostName Windows2008VM.vagrant.up
Port 5985
User vagrant
Password vagrant
This plugin requires version 1.6 of Vagrant or higher and this Driver
will check to see that the plugin is installed and the Vagrant version
is sufficient--if not a UserError is raised with a message describing
what action(s) to take.
If a WinRM …

Use the vagrant-winrm Vagrant plugin to resolve VM IP address.

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

Much <3 and thanks to @Annih for an epic turnaround. This is what makes
open source so rewarding.

Use RDPPort value from `vagrant winrm-config` for WinRM Transports.

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

This allows a `kitchen test` run to cleanly close any connection
resources on the remote instance before the instance is destroyed.

Close Transport connection in #destroy.

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

This update attempts to improve on
a2ef401fb5a644c96165ce836ff3e6379637a37f which remains a workaround
until the work of continuously publishing Bento boxes to Atlas is
completed.
The rationale and rules in the above mentioned commit remain, but now
only the platform name is checked. In other words, if the platform name
begins with one of the following (case-sensitive):
* `centos`
* `debian`
* `fedora`
* `freebsd`
* `opensuse`
* `ubuntu`
then the platform is assumed to have a Bento box, hosted in the
pre-determined S3 bucket.
References #165
References test-kitchen/test-kitchen#707
References test-kitchen/test-kitchen#663
References chef/chef-dk#382
References chef/chef-dk#378

Allow a fuzzier match for known Bento box names.

---

spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

this fixes winrm out of the box. before change c.vm.communicator would be set to winrm correctly but username and password would be prefixed with c.ssh. also add handling for additional winrm config settings

add handling for winrm communicator in username & password handling

---

spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

With the this small fix, the following example will work as expected:
```yaml
driver:
ssh:
shell: 'sh'
```
Related to: #131, bf38f9492798b995befc70723166ede8f3b3c96e

Fix config[:ssh] to be quoted properly

---

spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Fixes #171 
Updated Vagrantfile template so that now "customize" option has a default behavior for Vagrant providers which are not case listed.

Customize supports other vagrant providers, fixes #171

---

spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

I'm maintaining the vagrant-cloudstack plugin and got several request from colleagues to integrate it with kitchen.
I know that there is a kitchen-cloudstack plugin, but it lacks support for some of the features we use (e.g. not opening the firewall to 0.0.0.0/0, or customizing the user and private key to use with SSH). It also seems a bit of double work to implement two clients, one for vagrant and another for kitchen, when kitchen can leverage vagrant. Hence, this PR.
I did not update the README file, but I will be happy to do that if requested.

Add cloudstack support

---

README.md
spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Properly disables box update checking when box_check_update is false
Update documentation to reflect the actual default behavior of box update checking

Fixes box check update bug

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

Bento hosts its base boxes on https://atlas.hashicorp.com/bento
I'm unsure whether it's worth removing default_box_url, but from a class-api BC, keeping this in will still allow for monkey-patching new behaviours in.
Fixes #193

Use Bento's Atlas boxes by default if detected

---

spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

`memory` and `cpus` customization parameters are widely used in `.kitchen.yml` of different community cookbooks.
But currently it doesn't work for "parallels" provider, because `prlctl set` command doesn't support "memory" argument (it expects to get a "memsize" instead).
However, this provider actually supports  `memory` and `cpus` as customization shortcuts (it was implemented for similarity with virtualbox provider):
```ruby
config.vm.provider "parallels" do |prl|
prl.memory = 1024
prl.cpus = 2
end
```
So, this PR makes it possible to use `memory` and `cpus` for "parallels" provider.
cc: @fnichol

Parallels: Use "memory" and "cpus" customization shortcuts

---

.travis.yml

Ruby 1.9.3 is no longer supported, and the tests fail if you try and use it.

Ruby 1.9.3 is no longer supported

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Defaults to not setting, and therefore using the Vagrant default.

Add option for box_download_insecure to be passed to Vagrantfile

---

templates/Vagrantfile.erb

I've found hyperv customize code in my .kitchen.yml not applied. So I manually modified template/Vagrantfile.erb and now it works.
Testing environment:
- Windows 10 64-bit (build 10586 / version 1511) with Hyper-V platform enabled
- ChefDK 0.10.0
- Vagrant 1.8.1
- Kitchen 1.4.2

Add support for hyperv customize

---

README.md
lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Allows to use linked clones with Vagrant 1.8

Add linked_clone config option

---

README.md

Updating Readme to reflect changes to default boxes

---

spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

This PR fixes boolean values inside the `ssh:` configuration key. For example:
```yaml
---
driver:
ssh:
insert_key: false
```
This will create a Vagrantfile like the following:
```ruby
Vagrant.configure("2") do |c|
c.ssh.insert_key = "false"
end
```
Instead of:
```ruby
Vagrant.configure("2") do |c|
c.ssh.insert_key = false
end
```
This PR fixes that little problem.
Bug mentioned in #163.

Fix ssh boolean values in Vagrantfile template

---

README.md

There is a typo in README: "Parllels". 
Also I would recommend using the correct product name, which is "Parallels Desktop for Mac" (shortly - "Parallels Desktop").

Fix the name of "Parallels Desktop for Mac"

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

Setting up the new `chef_directory` interface within the Driver. Then with this directory we will allow the the instance to have a cache directory where omnitruck will download the artifacts, so we can cache the packages locally and avoid re-pulling down artifacts that you already have on your workstation.

Add a synced folder to persist chef omnibus packages

---

README.md
lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb
spec/spec_helper.rb

We are going to default to `C` Drive since vagrant does not know about
the environament variables of the guest VM.
Closes https://github.com/test-kitchen/kitchen-vagrant/issues/250

Fix cache directory on windows

---

lib/kitchen/driver/vagrant.rb

Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

add oracle as supported bento-box type

---

spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

We need to scape the back slashes in Ruby but also Vagrant requires to
scape them. So we need to double scape!

Vagrant requires also to scape slashes

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

We are not allow to use the DRIVE C: when sharing a folder in
vagrant/virtualbox because Windows doesn't like the fact that you have
the colon.
We now default to `/omnibus/cache` that Windows will understand as:
```
%SYSTEMDRIVE%/omnibus/cache
```

Change default cache dir for Windows

---

lib/kitchen/driver/vagrant.rb

After upgrading chef-dk to 0.18 which bumps ruby to 2.3.1, kitchen-vagrant breaks on windows when running in a bundled environment. Essentially vagrant is run in test-kitchen's ruby.
In the previous chef-dk ruby of 2.1.9, a bundled environment did not set the `GEM_HOME` variable so the problem code path here was never touched. Now on ruby 2.3.1, because GEM_HOME is present, kitchen-vagrant attempts to clean the path. This works fine on linux machines. However on windows, vagrant will use this altered path "as is" and its own attempts to prepend the path with the ruby in vagrant's omnibus install will be ignored.
From whatI can tell, not cleaning the path has no adverse side effects. Perhaps this is because newer versions of vagrant do a better job of cleaning the environment on its side - …

Don't alter the path during the bundler cleanup on windows

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

…
Signed-off-by: Matt Wrock <matt@mattwrock.com>

do not map the extra cache drive on non virtualbox windows

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

We are excluding FreeBSD systems and also adding the ability to disable
the `cache_directory` by setting it up to `false` in the `kitchen.yml`
file.
Example:
```yaml
platforms:
- name: ubuntu-12.04
driver:
cache_directory: false
```
Closes https://github.com/test-kitchen/kitchen-vagrant/issues/260
Closes https://github.com/test-kitchen/kitchen-vagrant/issues/256
Closes https://github.com/test-kitchen/kitchen-vagrant/issues/257
cc/ @test-kitchen/maintainers

Exclude freebsd and ability to disable cache dir

---

Rakefile
kitchen-vagrant.gemspec
lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

This should also fix Travis :)

Move to chefstyle

---

README.md

Updates and fixes, mostly around the move to using Bento boxes from Atlas. Also updated examples to use newer platforms and reduced the number of examples as we don't want to keep a canonical list in two places.

Updating readme examples for accuracy

---

templates/Vagrantfile.erb

LXC configuration allows for including files with common settings (see
`lxc.container.conf(5)`).  This is `lxc.include` directive differs
from other settings, in that multiple settings of the same key makes
sense.  Previously, a configuration of the form:
```
driver:
name: vagrant
provider: lxc
customize:
include: '/usr/share/lxc/config/ubuntu.common.conf'
include: '/usr/share/lxc/config/nesting.conf'
```
...would necessarily only include one of the files, as duplicate keys
are collapsed during YAML loading.  Since the existing code assumes
that all values are scalar, it was likewise impossible to set
`include` to an array.
Extend the supported syntax to allow:
```
driver:
name: vagrant
provider: lxc
customize:
include:
- '/usr/share/lxc/config/ubuntu.common.conf'
- …
```

Allow multiple "include" statements in LXC configuration

---

README.md
lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Adds support `vagrant-cachier` but doesn't make it default
- mostly fix #186, at least in spirit
- supersedes #200

Fix #186 (mostly) and make it easy to use vagrant-cachier

---

README.md
lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Add support for box_download_ca_cert

---

CHANGELOG.md
lib/kitchen/driver/vagrant_version.rb

Release 1.0.0

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

This will fix an issue for users trying to run on macos, it can already be achieved by setting the cache_directory to false in the kitchen.yml file but that is a work around.  This solves #280 for the OS's @cheeseplus mentioned.

Exclude cache directory mount on osx / macos instances because of issues on virtualbox

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

I got the following error message ([full error message](https://gist.github.com/Kuniwak/83e60be11445d1f859a5e58590c78afa)) when executing `kitchen list`:
```console
$ kitchen list
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'vagrant' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
This message said that "`kitchen-vagrant` was not installed," but `kitchen-vagrant` was listed by `bundle list` and `require("kitchen/driver/vagrant.rb")` did not raise `LoadError`.
I think this problem is caused by …

Fix a bug can be occurred when `instance` returns `nil`

---

templates/Vagrantfile.erb

This negates #289 
Not sure what tests look like but a sanity syntax check passed:
```
$ erb -x -T  '-' Vagrantfile.erb  | ruby -c
Syntax OK
```

Add support for all misc vagrant providers

---

README.md
lib/kitchen/driver/vagrant.rb

Adds the ability to override the location of the Kitchen cache to something other than '~/.kitchen/cache'.
The main driver here is that we map our home drives to a UNC path which is fine in the office, but quite slow over the VPN. As a result, I have to redirect many folder homes to a local path.

Adds ability to override Kitchen cache directory

---

lib/kitchen/driver/vagrant.rb

Tested with the following config:
```
---
driver:
name: vagrant
provider: lxc
provisioner:
name: chef_zero
platforms:
- name: xenial64-lxc
driver_plugin: vagrant
driver_config:
box: hrishikeshdate/xenial64
ssh:
insert_key: false
suites:
- name: mysuite
run_list:
- recipe[mycookbook::default]
```

Make kitchen package work

---

README.md

Add documentaion on how to disable `cache_directory`. As per https://github.com/test-kitchen/kitchen-vagrant/pull/262

README: add info about cache_directory disabling

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

Given what we've seen it's a better assumption to only enable the `cache_directory` by default for platforms we expect will work with shared folders, namely a subset of bento boxes. This has some advantages:
- only enable if the `box` is `bento/*` where * is a subset of bentos boxes
- simplify tests and logic due to above
This will change the default of `cache_directory` but does so in a way that minimizes frustration and maximizes delight. We're still pursuing an overall better way of caching to work around the limitations of shared folders but this should at least make the experience more pleasant out of the box.

Only enable the cache when using known bento boxes. Fix #296

---

lib/kitchen/driver/vagrant.rb

Due to some Windows shell vagaries, exact line regex matching on vagrant-winrm plugin is failing. Loosening up the regex just a little bit allows it to succeed. There's a very low probability of matching the wrong vagrant plugin, but it is possible I suppose.
Certain Windows shells are colorizing the output of the command `vagrant plugin list`, which is causing the match failure. Wild theory, could be a change due to Windows Anniversary Update, as they've been making fundamental changes to the command shells.

Fix detection of vagrant-winrm plugin.

---

templates/Vagrantfile.erb

Setup of WinRM options breaks Kitchen, `.kitchen.yml`:
```
driver:
name: vagrant
winrm:
username: Administrator
password: password
```
Error:
```
/.../.kitchen/kitchen-vagrant/.../Vagrantfile:4: syntax error, unexpected tIDENTIFIER, expecting keyword_end
```
Reason: missed quote around WinRM values in `Vagrantfile`

Fix bug in Vagrantfile template related to WinRM options (missed quote)

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

+ moved the setting of the default values for cache_directory up to the
default_config declaration section
+ added fast fail to `enable_cache?` for when a config declares the
cache_directory to be false per the documentation
+ simplified the cache_directory getter to return the cache_directory
only if `enable_cache?` criteria are met
+ some specs updated that expect to be caching, but did not meet
`enable_cache?` criteria (using a bento)
Fixes #307

turn off caching, even for bento boxes

---

Rakefile
kitchen-vagrant.gemspec

chefstyle is where style rules have been defined, so remove cane. If complexity analysis is desired in the future, it can be reenabled in a project-specific config for chefstyle (rubocop).

remove cane testing, chefstyle will handle

---

README.md

As suggested in #311 this PR adds a section in the readme listing Vagrant providers which are not officially supported but are technically known to kitchen-vagrant and may work.
Except for KVM/Libvirt I did not test if the providers are correct and working.
Fixes #311

Add list of unmaintained Vagrant providers

---

lib/kitchen/driver/vagrant.rb

Hi,
This patch sets up environmental variables which isolate the VirtualBox environment (configuration file, machine location, and IPC socket) and allow parallel creation of VirtualBox instances with vagrant.
Comments are welcome!

Parallel virtualbox

---

README.md
spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Currently the VagrantFile template supports when using the VirtualBox provider to attach **one** additional disk:
```yaml
driver:
customize:
createhd:
filename: /tmp/disk1.vmdk
size: 1024
storageattach:
storagectl: SATA Controller
port: 1
device: 0
type: hdd
medium: /tmp/disk1.vmdk
```
This PR extends this to allow to attach **multiple** additional disks by using an array syntax:
```yaml
driver:
customize:
createhd:
- filename: /tmp/disk1.vmdk
size: 1024
- filename: /tmp/disk2.vmdk
size: 2048
storageattach:
- storagectl: IDE Controller
port: 1
device: 0
type: hdd
medium: /tmp/disk2.vmdk
- storagectl: IDE Controller
port: 1
device: 1
type: hdd
medium: /tmp/disk2.vmdk
```
The original syntax is still supported, for backward compatibility.

Support to create/attach multiple additional VirtualBox disks

---

lib/kitchen/driver/vagrant.rb

The fix for running create and destroy in parallel on Virtualbox
exacerbates and existing problem with deeply nested, long directory
names that trips on Windows' 256 character path limit. Disabling
parallel runs on Windows hosts until such time as maybe UNC paths are
tested.

turn off parallel vbox when run on Windows hosts

---

lib/kitchen/driver/vagrant.rb

This change exacerbated an existing path-too-long problem in Windows [#210] and introduced a few new undesired behaviors as default. (#322, kitchen VMs running entirely disconnected from the Virtualbox manager, and `gui: true` no longer working.)
Reverting in favor of working a future PR for Virtualbox parallelism as optional. (Which is tricky given that we'll need to tinker with `@serial_actions` without using `no_parallel_for`.)

revert parallelism for Virtualbox

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

This omits "kitchen-#{something}" from the vagrant root directories that will appear under .kitchen/kitchen-vagrant. 
[Windows users will run into a path length limit of 260 characters.](https://github.com/test-kitchen/kitchen-vagrant/issues/210) We have been repeating in the directory structure "kitchen-" and the basename of kitchen-root--the directory that contains the .kitchen.yml which most of the time works out to be the name of the cookbook being tested. This made for meaningful if verbose names for virtual machines so as to correlate a machine running in a Vagrant-supported hypervisor to a test-kitchen config.
The inclusion of this string was _not_ for any unique identifier to avoid naming collusions within the hypervisor. This change should be safe for an upgrade for kitchens that …

shorten the directory name for vagrant_root

---

templates/Vagrantfile.erb

This fix tries to differentiate strings from non-strings when using kitchen-vagrant & WinRM. It likely addresses https://github.com/test-kitchen/kitchen-vagrant/issues/327 but also an issue I observed when using `retry_delay` and `retry_limit`.
I believe with https://github.com/WinRb/WinRM/commit/a4ab853b04c04b8cf38ed0565fdf01290040f89e in WinRM with switching from `FixNum` to `Integer`, certain features, notably `retry_delay` and `retry_limit`, no longer work when passed in Test Kitchen. This is likely caused by https://github.com/test-kitchen/kitchen-vagrant/pull/306 will always treat set configuration for WinRM as a string. 
First observed when using Vagrant 2.0.0 (which includes 2.2.3 of https://github.com/WinRb/WinRM and Ruby 2.4.0) and latest stable Chef DK (2.3.4).
``` …
```

For WinRM options, only treat strings as strings. 

---

README.md
spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

This PR allows to use storagectl in customize section.
This enables various possibilites, such as changing the portcount of a disk controller to be able to attach more disks to it, or create new disk controllers.

virtualbox: Allow to use storagectl in customize section

---

lib/kitchen/driver/helpers.rb
lib/kitchen/driver/vagrant.rb
support/hyperv.ps1

This improves Hyper-V support in a few ways:
- borrowed and enhanced code from kitchen-hyperv to detect sane Hyper-V switch defaults
- environment variable  `KITCHEN_HYPERV_SWITCH` is checked/used and takes precedence over above code
- shared folders are disabled by default for bento Hyper-V boxes

Improving Hyper-V support/defaults

---

kitchen-vagrant.gemspec
lib/kitchen/driver/vagrant.rb

Signed-off-by: Stuart Preston <stuart@chef.io>
On a Windows 10 (build 16299) machine, the name of the default Hyper-V switch is `Default Switch`. If the switch is specified in the .kitchen.yml as per the documentation (see below example) then there is no issue with the generated Vagrantfile:
```
network:
- ["public_network", bridge: "Default Switch"]
```
However, when the default configuration is used without specifying the above, the following entry is generated in the Vagrantfile:
```
c.vm.network(:public_network, bridge: Default Switch)
```
In turn this leads to Vagrant not being able to validate the file correctly, returning the following error:
```
Vagrantfile:6: syntax error, unexpected tCONSTANT, expecting keyword_do or '{' or '('
etwork, bridge: Default Switch)
^
Vagrantfile:15: …
```

Hyper-V: Ensure default switch name is always wrapped in quotes

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

Fix #349 - we'll grab hardenedbsd-11 from the bento org now

Fixing #349 - allow bento/hardenedbsd

---

spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Fixes #365 
This adds the `name` parameter for the VirtualBox provider configuration in the generated Vagrantfile. This only affects the UI and restores the old naming convention which make finding the VMs in the UI more convenient.

Fix #365 - add name for virtualbox instances

---

templates/Vagrantfile.erb

Fixes #367
This PR allows a VM instance created by kitchen-vagrant and the Hyper-V provider to be identified by its instance name.  This makes it easier to identify the running VM when looking at the Hyper-V running configuration (either via UI or PowerShell).
The actual hostname (Linux) or NetBIOS name of the machine (if Windows) is not affected by this change, it only affects the display name in Hyper-V manager.
Given a base folder name of *hypervtest*, a *default* suite and a platform named *windows2012r2*, the generated name is as follows: `kitchen-hypervtest-default-windows2012r2`
Signed-off-by: Stuart Preston <stuart@chef.io>

Adding a per-instance generated vmname for Hyper-V

---

kitchen-vagrant.gemspec

Slim the size of the gem by removing spec files

---

lib/kitchen/driver/vagrant.rb

1. ~This is pending on https://github.com/hashicorp/vagrant/pull/10263 getting merged and released~
1. We need some logic for what to do when vagrant is between `2.1.5` and `2.1.7`. Between those versions vagrant does not require `vagrant-winrm` but it will not work because the code from https://github.com/hashicorp/vagrant/pull/10263 is not in there
Signed-off-by: tyler-ball <tball@chef.io>

Newest vagrant no long requires vagrant-winrm plugin

---

spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Fixes #388
As mentioned in that issue, modifying the VM to have audio set to "none" will disable sound for the VM and prevent VirtualBox from connecting to the host's audio which really cramps a user's style when they're listening to something over bluetooth headphones.
This change opts to be simple-but-repetitive in the tests to include the new default in each example VM config.
Also resolves a deprecation notice about the use of `Fixnum`.

disable audio in virtualbox by default

---

README.md

The documentation that was missing from #392.

add documentation for enabling sound

---

lib/kitchen/driver/vagrant.rb

- Updated vagrant.rb to read from `VAGRANT_WSL_WINDOWS_ACCESS_USER_HOME_PATH` if set
- [More information](https://www.vagrantup.com/docs/other/wsl.html#vagrant_wsl_windows_access_user_home_path)
I have no experience with ruby/vagrant/chef

Added WSL support

---

lib/kitchen/driver/vagrant.rb

Bento now includes an amazonlinux-2 box so we should use that. This should be zero impact to anyone using one of the previous images as they'll already be manually defining the box.

Support using bento/amazonlinux-2 when specifying just amazonlinux-2 platform

---

kitchen-vagrant.gemspec

2.0 will break nothing that impacts this plugin

Loosen the Test Kitchen dep to allow 2.0

---

spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Fixes bug introduced by #366. By specifying a name in the Vagrantfile,
we lose uniqueness added by the [Vagrant SetName
class](https://github.com/hashicorp/vagrant/blob/85acf0cac724ef4bfda593a66e0c17f7e4110da0/plugins/providers/virtualbox/action/set_name.rb#L29).
This PR restores uniqueness.
Closes #376.

Restores vm name uniqueness.

---

templates/Vagrantfile.erb

As part of https://github.com/test-kitchen/kitchen-vagrant/commit/b018a077b93cc343f29c43e9eec2366f38eefe61 to introduce unique names a uuid was added to the generated vagrantfile. This causes problems with hyper-v which relies on names being 100 characters or less otherwise it throws an exception.
This commit takes the current naming system and substrings it to fit within this character limit. It may be a better idea to use time ticks as these would end up with us substringing less due to their shorter nature (the UUID is a third of the allowed length by itself)
1.5.2
2.2.5
2.2.5
Windows 10
#403

Hyper-v Name Length fix

---

.travis.yml
CHANGELOG.md
Guardfile
Rakefile
kitchen-vagrant.gemspec
lib/kitchen/driver/helpers.rb
lib/kitchen/driver/vagrant.rb
lib/kitchen/driver/vagrant_version.rb
spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Autocorrect with Chefstyle which uses Ruby 2.3-isms. Add a required ruby version to the gemspec for the first time.

Release 1.6.0 requiring Ruby 2.3+ and fixing Chefstyle issues

---

README.md
lib/kitchen/driver/vagrant.rb

Signed-off-by: Corey Hemminger <hemminger@hotmail.com>
Added features for auto updating vagrant box images to latest and auto pruning specific box images

Added features for auto updating and pruning vagrant box images

---

lib/kitchen/driver/vagrant.rb

This saves us memory by not allocating an object for the match

Use match? when we don't need the match data

---

lib/kitchen/driver/vagrant.rb

When we're pruning a box make sure not to fail if there's an active box
preventing the full prune.

Don't fail if active boxes can't be pruned

---

lib/kitchen/driver/vagrant.rb

When performing a `vagrant box update --box BOXNAME`, the CLI command will exit with code 1 if the named box does not already exist. In our use case, we can ignore that error and happily continue, since our later vagrant up command will download the box if missing. 
I considered explicitly listing boxes rather than ignoring an error, but that would introduce a performance penalty to every run.
Fixes #425

Ignore error if box not found when updating

---

Gemfile
Rakefile
kitchen-vagrant.gemspec

Remove the test / release files we're not using anymore

Remove github changelog generator & countloc

---

CHANGELOG.md
README.md
lib/kitchen/driver/vagrant.rb
lib/kitchen/driver/vagrant_version.rb
spec/kitchen/driver/vagrant_spec.rb

Rebased and updated version of changes in #453 with original changes by @gaelik still in the merge history.
Description from #453
```
This change would add the ability for people creating their own boxes to use the cached version of the chef client like the bento machines are doing. That saves a lot of time and bandwitdh on slow and offshore connections that need to download the chef client for windows every time they run a test.
```
This update rebases #453 from current upstream `master` and additionally adds spec testing and README wording updates for `use_cached_chef_client` configuration.

Updated use_cached_chef_client PR

---

CHANGELOG.md
README.md
lib/kitchen/driver/vagrant.rb
lib/kitchen/driver/vagrant_version.rb

This change would add the ability for people creating their own boxes to use the cached version of the chef client like the bento machines are doing. That saves a lot of time and bandwitdh on slow and offshore connections that need to download the chef client for windows every time they run a test.
List any existing issues this PR resolves

allows using cached_copy of the chef-client like with bento boxes

---

.github/dependabot.yml
.github/workflows/linters.yml

Signed-off-by: sachin007jain <sachin.jain@chef.io>
Using Chefstyle for linting instead of Rubocop
- https://github.com/chef/chef-workstation/issues/2522

Use chefstyle linting

---

spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

The final Vagrant file should be compatible with Ruby 2.7 and 3,
so it should look like that:
```diff
- c.vm.network(:forwarded_port, {:guest=>443, :host=>2443})
+ c.vm.network(:forwarded_port, :guest=>443, :host=>2443)
```
#476
If you have not included a conventional commit message this can be fixed on merge.

Ruby 3 compatibility for network configuration

---

lib/kitchen/driver/vagrant.rb

Signed-off-by: Corey Hemminger <hemminger@hotmail.com>
This is required if you have multiple boxes of the same name from multiple providers such as virtualbox and parallels. Without the provider flag it throws an error not knowing which one to update or prune. Adding the flag doesn't change original behavior either.
bugfix

add provider to update and prune commands

---

lib/kitchen/driver/vagrant.rb

adds `-arm64` to bento box name automatically if on an arm64 cpu host
List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant
If you have not included a conventional commit message this can be fixed on merge.

_feat_: add arm64 to bento box name

---

CHANGELOG.md
lib/kitchen/driver/vagrant_version.rb

Signed-off-by: Ashique P S <Ashique.saidalavi@progress.com>
Release 1.14.0
- Add arm64 to bento box name [#483](https://github.com/test-kitchen/kitchen-vagrant/pull/483) ([@Stromweld](https://github.com/Stromweld))
List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant
If …

Release 1.14.0

---

lib/kitchen/driver/vagrant.rb

When an older box version is still in use by a vagrant box the prune command then prompts for user input to continue after warning of box that is older but in use  but throws an error since their is no tty attached. This forces it to continue with prune and not prompt. Older boxes that are still associated with active vagrant machines are not removed.

_fix_add force for prune command

---

README.md
lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

added vagrant cpu architecture support when specifying boxes and providers
https://developer.hashicorp.com/vagrant/vagrant-cloud/boxes/architecture
https://app.vagrantup.com/bento/boxes/ubuntu-23.10
When not specified Vagrant defaults to the system CPU architecture for box downloads

add vagrant architecture support

---

.markdownlint.yaml
.rubocop.yml
CHANGELOG.md
README.md
kitchen-vagrant.gemspec
lib/kitchen/driver/vagrant_version.rb

Require Ruby 3.0 + release 2.0 version of this plugin

---

.github/workflows/lint.yml
.rubocop.yml
Gemfile
Rakefile
lib/kitchen/driver/vagrant.rb

adding utm and qemu to list of providers not safe to use omnibus  cache as a shared folder. Those providers use qemu and try to mount as 9p file system. All RHEL variantes don't support 9p filesystem and requires recompiling of kernel to enable kernel modules or installing kernel from elrepo which defeats having a standard rhel based install.
Fix cookstyle linting

fix: Add utm provider to list of not safe providers for omnibus cache

---

.github/workflows/lint.yml
Rakefile
spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

* Use JSON.parse(value.to_json).to_s approach to ensure consistent hash
string representation across Ruby versions
* Update test expectations to use modern {"key": value} JSON-style syntax
* Fixes test failures occurring with Ruby 3.4's updated hash.to_s behavior
Signed-off-by: Dan Webb <dan.webb@damacus.io>

fix: update hash syntax for Ruby 3.4 compatibility
