test-kitchen/kitchen-vagrant

.travis.yml
Gemfile
Guardfile
Rakefile
kitchen-vagrant.gemspec
lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb
spec/spec_helper.rb
templates/Vagrantfile.erb

Not a small nor simple task. The insane complexity is buried in the
combinatorics of configuration combinations and ERb template rendering
combinations.

Add full spec coverge to codebase.

---

spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Only fair to support both options commonly (and in the documentation) configured together.

Translate CPU count for VMWare

---

kitchen-vagrant.gemspec
lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

This commit adds 2 new peices of metadata: plugin version and driver API
version.

Add plugin metadata to Driver.

---

README.md

corrected grammar error

---

templates/Vagrantfile.erb

Little tidying up.
Based on a comment we received once when adding cloudstack: https://github.com/test-kitchen/kitchen-vagrant/pull/167#discussion_r39869582

HyperV acts as OpenStack, CloudStack

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

See #218 for (a lot of :wink:) details

Make vagrant binary a parameter

---

templates/Vagrantfile.erb

A very simple change to support vagrant-ovirt3 provider (https://github.com/myoung34/vagrant-ovirt3).

Add support for ovirt3 vagrant provider

---

.travis.yml

This fixes travis failures and creates only one travis hook.

Bump travis rubies to the modern age

---

templates/Vagrantfile.erb

Adds boolean value support to ssh config option
Fixes #236
Credit: @jsirex - [Original Fix](https://github.com/test-kitchen/kitchen-vagrant/issues/236#issuecomment-234486655)

Fix generated Vagrantfile type issues

---

CHANGELOG.md
lib/kitchen/driver/vagrant_version.rb

Preparing 0.21.0 release

---

CHANGELOG.md
lib/kitchen/driver/vagrant_version.rb

Release version 0.21.1

---

README.md
spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Started with https://github.com/test-kitchen/kitchen-vagrant/pull/178 and added the requested feedback (testing + documentation)

Virtualbox storage via createhd and storageattach

---

templates/Vagrantfile.erb

Work initially done by @i11 in https://github.com/test-kitchen/kitchen-vagrant/pull/179 - this is just rebased against master.

Fix quoting for cloud providers (redux #179)

---

spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Fix #175. Ability to set cpuidset for vbox

---

spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Fix #237 - fix `false` for box_check_update

---

README.md

added -- to make it a command line param

added -- to make it a command line param

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

- Fixes #282 
- collapse freebsd and macOS/osx logic
- enhance tests

Loosen matching for freebsd platforms

---

CHANGELOG.md
lib/kitchen/driver/vagrant_version.rb

Release v1.0.1

---

CHANGELOG.md
lib/kitchen/driver/vagrant_version.rb

Release 1.0.2

---

CHANGELOG.md
lib/kitchen/driver/vagrant_version.rb

Release 1.1.0

---

CHANGELOG.md
lib/kitchen/driver/vagrant_version.rb

Release 1.1.1

---

CHANGELOG.md
lib/kitchen/driver/vagrant_version.rb

Release 1.2.1

---

CHANGELOG.md
README.md
lib/kitchen/driver/vagrant_version.rb

Prepping 1.2.2 release

---

README.md
templates/Vagrantfile.erb

Add the support for Linked Drive for Hyper-V in the vagrantfile.erb

Adding support for HyperV Differencing_disk

---

.travis.yml

Updating travis config

---

CHANGELOG.md
lib/kitchen/driver/vagrant_version.rb

Release 1.3.2

---

README.md

Would have been tricky to have two disks with the same name when it came time to actually use them.

Fix disk examples

---

.travis.yml
Gemfile
Rakefile
kitchen-vagrant.gemspec

avoid the giant dep mess it brings in.

Move github changelog generator to the gemfile and skip install in testing

---

spec/kitchen/driver/vagrant_spec.rb

Adding the lifecycle hooks stub to fix tests

---

CHANGELOG.md
lib/kitchen/driver/vagrant_version.rb

Release 1.3.3

---

spec/kitchen/driver/vagrant_spec.rb
templates/Vagrantfile.erb

Fix #371, change require => load

---

CHANGELOG.md
lib/kitchen/driver/vagrant_version.rb

Release 1.3.4

---

Gemfile
Guardfile
Rakefile
lib/kitchen/driver/vagrant.rb
lib/kitchen/driver/vagrant_version.rb
spec/kitchen/driver/vagrant_spec.rb

Signed-off-by: tyler-ball <tball@chef.io>

Updating for new Chefstyle rules

---

lib/kitchen/driver/vagrant.rb
spec/kitchen/driver/vagrant_spec.rb

Signed-off-by: Mark E. Schill <Mark.Schill@cmschill.net>

Allows for windows hostnames up to 15 characters

---

.travis.yml
lib/kitchen/driver/vagrant.rb

require_relative is slightly faster

Use require_relative instead of require

---

Guardfile
Rakefile
kitchen-vagrant.gemspec
lib/kitchen/driver/vagrant.rb
lib/kitchen/driver/vagrant_version.rb
spec/kitchen/driver/vagrant_spec.rb
spec/spec_helper.rb

These aren't necessary in Ruby 2+

Remove encoding comments

---

.github/workflows/ci.yml

Update GitHub actions to cache gems / test Ruby 3

---

.rubocop.yml
CODE_OF_CONDUCT.md
README.md
Rakefile
example/kitchen.vagrant.yml

Run rubocop at Ruby 2.5 level (not 2.4)
Remove an extra description in the rakefile
Show the CI badge for master only
Add a code of conduct file

More misc testing updates

---

lib/kitchen/driver/vagrant.rb

Add support for Alma Linux Bento boxes

---

kitchen-vagrant.gemspec

Support Test Kitchen 3.0

---

lib/kitchen/driver/vagrant.rb

We're producing these bento boxes now

Support rockylinux and springdalelinux bento boxes

---

CHANGELOG.md
lib/kitchen/driver/vagrant_version.rb

Signed-off-by: Ashique P S <Ashique.saidalavi@progress.com>
Release 1.12.0
The changes include:
- Support for Ruby 3.1
- Using chef style listing
List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant
If you have not included a conventional commit message this can be fixed …

Release 1.12.0

---

CHANGELOG.md
lib/kitchen/driver/vagrant_version.rb

Signed-off-by: Vikram Karve <vikram.karve@progress.com>
If you have not included a conventional commit message this can be fixed on merge.

Prep to release 1.12.1

---

.github/workflows/publish.yml

old name is depreacted for new googleapis org
List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant
If you have not included a conventional commit message this can be fixed on merge.

fix action name

---

lib/kitchen/driver/vagrant.rb

Reverts test-kitchen/kitchen-vagrant#511

Revert "fix: add oracle linux to bento box list"
